// SPDX-License-Identifier: MIT

use serde_json::json;
use std::error::Error;
use sts2_harness::context_memory::{MemoryCorpus, MemoryScope};
use sts2_harness::provider_session::NativeCapabilities;

fn main() -> Result<(), Box<dyn Error>> {
    let scope = || {
        MemoryScope::new(
            "fixture-project",
            "fixture-run",
            "fixture-episode",
            "fixture-agent",
        )
    };
    let default = MemoryCorpus::new(scope())?.capabilities();
    let mut restricted = MemoryCorpus::with_limits(scope(), 16, 4096)?.capabilities();
    restricted.effective_limits.max_candidates = 8;
    restricted.effective_limits.max_results = 4;
    restricted.effective_limits.max_selected = 2;
    restricted.effective_limits.optional_byte_budget = 1024;
    restricted.effective_limits.max_source_bytes = 1024;
    restricted.effective_limits.max_sources_per_job = 2;
    restricted.effective_limits.max_job_input_bytes = 2048;
    restricted.effective_limits.max_summary_output_bytes = 512;
    restricted.effective_limits.max_query_bytes = 1024;
    restricted.effective_limits.max_lineage_depth = 1;
    restricted.effective_limits.max_global_memory_bytes = 4096;
    restricted.effective_limits.max_global_memory_jobs = 2;
    restricted.effective_limits.max_retention_resources = 16;
    restricted.effective_limits.max_retention_bytes = 4096;
    restricted.effective_limits.max_cache_entries = 16;
    restricted.effective_limits.max_review_records = 16;
    restricted.effective_limits.max_memory_bindings = 16;
    restricted.effective_limits.max_usage_attempts = 16;
    restricted.binding.descriptor_sha256 = restricted.descriptor_digest();
    let mut disabled = MemoryCorpus::with_limits(scope(), 16, 4096)?;
    disabled.set_enabled(false);
    let disabled = disabled.capabilities();
    let session_default = NativeCapabilities::fixture();
    let mut session_restricted = NativeCapabilities::fixture();
    session_restricted.effective_limits.max_completed_turns = 8;
    session_restricted.effective_limits.max_session_items = 16;
    session_restricted.effective_limits.max_history_ttl_seconds = 3600;
    session_restricted.effective_limits.max_dependencies = 8;
    session_restricted.effective_limits.max_events = 16;
    session_restricted.effective_limits.max_operations = 16;
    session_restricted.effective_limits.max_prepared = 16;
    session_restricted.effective_limits.max_candidates = 2;
    session_restricted.effective_limits.max_maintenance_jobs = 1;
    session_restricted.effective_limits.max_frame_bytes = 4096;
    session_restricted.effective_limits.max_history_bytes = 4096;
    session_restricted.effective_limits.max_prepared_bytes = 4096;
    session_restricted.effective_limits.max_suffix_bytes = 2048;
    session_restricted.effective_limits.max_output_schema_bytes = 1024;
    session_restricted.effective_limits.max_method_bytes = 64;
    session_restricted.effective_limits.max_json_depth = 16;
    session_restricted.binding.descriptor_sha256 = session_restricted.descriptor_digest();
    let mut session_disabled = NativeCapabilities::fixture();
    session_disabled.enabled_methods.clear();
    session_disabled.binding.descriptor_sha256 = session_disabled.descriptor_digest();
    default.validate()?;
    restricted.validate()?;
    disabled.validate()?;
    session_default.validate()?;
    session_restricted.validate()?;
    if session_disabled.validate().is_ok() {
        return Err("the pinned producer must reject an empty-method native descriptor".into());
    }
    let memory = [
        ("default", default),
        ("restricted", restricted),
        ("disabled", disabled),
    ]
    .into_iter()
    .map(|(name, descriptor)| {
        json!({"name": name, "descriptor": descriptor, "producer_descriptor_valid": true,
                "record": descriptor.effective_limit_record()})
    })
    .collect::<Vec<_>>();
    let session = [
        ("default", session_default),
        ("restricted", session_restricted),
        ("disabled", session_disabled),
    ]
    .into_iter()
    .map(|(name, descriptor)| {
        json!({"name": name, "descriptor": descriptor, "producer_descriptor_valid": name != "disabled",
            "record": descriptor.effective_limit_record()})
    })
    .collect::<Vec<_>>();
    let fixture = json!({
        "producer_revision": "f8015e52ccb530e60d722283ef2b063da372169b",
        "evidence": "original synthetic descriptors and records generated by the pinned harness library; no provider or native process",
        "restricted_profile": "MemoryCorpus(16,4096) plus explicitly reduced public descriptor ceilings; session public descriptor ceilings reduced. Rebound and validated by the producer. These are contract vectors, not provisioned runtime profiles.",
        "disabled_session": "Empty-method synthetic descriptor is rejected by NativeCapabilities::validate; its producer-generated record exercises disabled admission only and must not be treated as an attachable native profile.",
        "memory": memory,
        "session": session
    });
    println!("{}", serde_json::to_string_pretty(&fixture)?);
    Ok(())
}
